version: '2'
services:
  squid:
    image: sameersbn/squid
    volumes:
    - ./squid.conf:/etc/squid3/squid.conf
    - ./squid.passwords:/etc/squid3/passwords

  logstash:
    build:
      context: .
      dockerfile: Dockerfile_logstash
    command: > 
      logstash --debug -e '
        input { 
          cloudhub { 
            domain => "${CLOUDHUB_DOMAIN}" 
            username => "${CLOUDHUB_USERNAME}" 
            password => "${CLOUDHUB_PASSWORD}"
            interval => 10 # optional, default 300
            startTime => 0 # optional, default 0
          } 
        } output { stdout {} }'
